version: '3.8'

services:
  tor-anonymizer:
    build: .
    container_name: tor-anonymizer
    restart: unless-stopped
    ports:
      - "9050:9050"  # Tor SOCKS port
      - "9051:9051"  # Tor control port
    volumes:
      - ./logs:/app/logs
      - ./tor_data:/app/tor_data
      - ./settings.json:/app/settings.json:ro
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "--socks5-hostname", "localhost:9050", "-f", "http://httpbin.org/ip"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Web interface for monitoring
  tor-monitor:
    image: nginx:alpine
