version: '3.8'

services:
  tor-anonymizer:
    build: .
    container_name: tor-anonymizer
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Rome
    cap_add:
      - NET_ADMIN
      - NET_RAW

  monitoring:
    image: python:3.9
    container_name: tor-monitoring
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: python3 -m tor_anonymizer --monitor
    depends_on:
      - tor-anonymizer
